Closes #138: empty seq frame raises errors
cdisc-org/cdisc-rules-engine pull request #144
Opened 2022-09-28 09:41 UTC by sityaevDI

2022-09-28 09:54 UTC, alexfurmenkov commented on tests/unit/test_actions.py
> +def test_empty_sequential_not_raise_errors():
Let's just call the test like `test_empty_sequential`

2022-09-28 09:55 UTC, alexfurmenkov commented on tests/unit/test_actions.py
> +    assert result.errors[3]._sequence is None
Instead of checking the protected attribute, check the whole result. Create the expected result and compare it with the actual result.

2022-09-28 09:55 UTC, alexfurmenkov requested changes
Test: Instead of checking the protected attribute, check the whole result. Create the expected result and compare it with the actual result.

2022-10-04 08:28 UTC, sityaevDI commented on cdisc_rules_engine/models/actions.py
> +    def _sequence_exists(sequence: pd.Series, row_name: Hashable) -> bool:
we can hint it as `str` but pandas series name has `Hashable` type and we will have method call marked in IDE like

> Expected type `str` got `Hashable` instead

2022-10-04 09:40 UTC, alexfurmenkov commented on cdisc_rules_engine/models/actions.py
> +    def _sequence_exists(sequence: pd.Series, row_name: Hashable) -> bool:
okay

2022-10-04 09:41 UTC, alexfurmenkov approved these changes

2022-10-11 11:44 UTC, merged