Add test functionality to core.
cdisc-org/cdisc-rules-engine pull request #232
Opened 2022-12-14 13:38 UTC by nhaydel

This PR adds the ability for rule authors to test a rule using the rule engine. The test function takes a json rule and the json datasets provided by the rule editor and runs the rule locally, producing the same excel output that the run validation function would produce. To run:

```
python core.py test -s sdtmig -v 3-4 -dp scripts/ae.json -r scripts/authored_whodrug_hierarchy_validation_rule.json --meddra ./meddra/ --whodrug ./whodrug/
```

2022-12-15 21:51 UTC, gcampion-cdisc commented
Readme should be updated with description for validation options `-r, --rules TEXT`

2022-12-19 11:41 UTC, alexfurmenkov commented
What is the difference between this command and `validate`?

2022-12-19 12:38 UTC, nhaydel commented
> What is the difference between this command and `validate`?

This command is meant to allow users (mostly me trying to debug blocked rules) to run rules they have written in the rule editor that are not published. The only real difference between the two commands is that this one takes in a rule json file and a dataset json file and just validates that rule and dataset or set of datasets. I imagine rule authors can also use this to test engine functionality that is not yet in the editor like using external dictionaries

2022-12-19 14:34 UTC, gcampion-cdisc requested changes

2022-12-19 14:42 UTC, nhaydel commented on core.py
> +from cdisc_rules_engine.models.test_args import TestArgs
Added. If you are testing. Make sure that the datasets file looks like:
```
{
    "datasets": [{
      "filename": "cm.xpt",
      "label": "Concomitant/Concurrent medications",
      "domain": "CM",
      "variables": [...
```

2022-12-19 14:52 UTC, gcampion-cdisc commented on core.py
> +from cdisc_rules_engine.models.test_args import TestArgs
i think this should also be mentioned in the readme

2022-12-19 14:56 UTC, nhaydel commented
> > > What is the difference between this command and `validate`?
> > 
> > 
> > This command is meant to allow users (mostly me trying to debug blocked rules) to run rules they have written in the rule editor that are not published. The only real difference between the two commands is that this one takes in a rule json file and a dataset json file and just validates that rule and dataset or set of datasets. I imagine rule authors can also use this to test engine functionality that is not yet in the editor like using external dictionaries.
> > Note: This does come from a request from the rule authors to have a way to use the engine to test unpublished rules
> 
> Is there a reason why these can't use the same cli command?

Technically they could be, but I think it is better not to overload the validate command. The inputs are different, and I imagine the output may change in the future as well.

2022-12-19 14:57 UTC, gcampion-cdisc approved these changes
Sorry, my original review comment was delayed because I didn't realize it was still private (pending) until today.
I've made 2 more comments, but otherwise looks good and is working well.

2022-12-20 20:24 UTC, merged