Allow dummy data service to get standard and standard_version
cdisc-org/cdisc-rules-engine pull request #464
Opened 2023-07-13 17:34 UTC by nhaydel

Steps to test:

Run a test validation with the provided rule and dataset file. Verify that the provided domains are not skipped

2023-07-13 20:06 UTC, gerrycampion requested changes
Good, except I think we need to return an error with a useful message instead of a scope skip if the library standard and version are missing, right?

Also, do you think it would be a good idea for the rule editor to use the latest standard/version provided in the Rule's Authorities Standards if one is not provided in the test data?

2023-07-13 20:14 UTC, nhaydel commented
> Good, except I think we need to return an error with a useful message instead of a scope skip if the library standard and version are missing, right?
> 
> Also, do you think it would be a good idea for the rule editor to use the latest standard/version provided in the Rule's Authorities Standards if one is not provided in the test data?

1. Do you think that message should be thrown when the test endpoint is called? Do we want to require a standard and version are provided
2. I think defaulting to the latest standard/version provided in the authorities section would be cool, but I would ask the rule authors if they would find it useful before implementing it

2023-07-13 20:23 UTC, gerrycampion commented
I'm not sure how errors currently work in the Engine, but I think it should be an `execution_error`. Lib standard/version should only be required when an operation/operator/scope etc needs the library.

2023-07-14 15:57 UTC, gerrycampion approved these changes

2023-07-17 12:29 UTC, merged