ISS-459: Fix issues reading define 2.0 domain metadata
cdisc-org/cdisc-rules-engine pull request #470
Opened 2023-07-17 19:00 UTC by nhaydel

Steps to test:

1. Run unit tests

2023-07-17 19:59 UTC, RamilCDISC commented on tests/QARegressionTests/test_core/test_define_read.py
Can you please move this test file from test_core to a new folder 'test_issues'  in QAResgressionTests. I will add my other tests there too

2023-07-17 20:10 UTC, gerrycampion commented on tests/unit/test_define_xml_reader.py
> +    "filename", [(test_define_file_path), (test_define_2_0_file_path)]
you should also add this parametrization to `test_extract_domain_metadata` to verify class and is_non_standard

2023-07-17 20:11 UTC, gerrycampion requested changes
one item, otherwise looks good

2023-07-18 00:18 UTC, nhaydel commented on tests/QARegressionTests/test_core/test_define_read.py
Actually, I think I am going to remove these tests because this and the unit tests are essentially doing the same thing. Are you ok with that?

2023-07-18 15:26 UTC, merged