ISS-257: Add define_variable_has_comment attribute to support comment existence check
cdisc-org/cdisc-rules-engine pull request #519
Opened 2023-08-14 20:19 UTC by nhaydel

Steps to test:

Run unit tests

2023-08-14 23:52 UTC, nhaydel commented
@gerrycampion since this Issue can be solved multiple ways:
1. Using the expected_variables operation in conjunction with the new define_variable_has_comment attribute
2. Using the result of merging define variable metadata with library variable metadata

And I believe we agreed that we prefer option 2 since it is more robust. I will take this time to implement the new rule type for define variable metadata with library variable metadata. If you agree with this approach I will convert this PR to draft until I have implemented the additional rule type

2023-08-15 16:28 UTC, gerrycampion commented
> @gerrycampion since this Issue can be solved multiple ways:
> 
> 1. Using the expected_variables operation in conjunction with the new define_variable_has_comment attribute
> 2. Using the result of merging define variable metadata with library variable metadata
> 
> And I believe we agreed that we prefer option 2 since it is more robust. I will take this time to implement the new rule type for define variable metadata with library variable metadata. If you agree with this approach I will convert this PR to draft until I have implemented the additional rule type

Yes, agreed

2023-08-15 16:51 UTC, nhaydel commented
> > @gerrycampion since this Issue can be solved multiple ways:
> > 
> > 1. Using the expected_variables operation in conjunction with the new define_variable_has_comment attribute
> > 2. Using the result of merging define variable metadata with library variable metadata
> > 
> > And I believe we agreed that we prefer option 2 since it is more robust. I will take this time to implement the new rule type for define variable metadata with library variable metadata. If you agree with this approach I will convert this PR to draft until I have implemented the additional rule type
> 
> Yes, agreed

Added new rule type: `Define Item Metadata Check against Library Metadata`

2023-08-16 17:50 UTC, gerrycampion requested changes

2023-08-16 17:50 UTC, gerrycampion commented on cdisc_rules_engine/dataset_builders/define_variables_with_library_metadata.py
> +        "define_variable_mandatory",
add "define_variable_has_comment",

2023-08-16 17:50 UTC, gerrycampion commented on resources/schema/MetaVariables.md
> +## define_variable_has_comment
Need to also create schema and documentation for `define_vlm_has_comment`

2023-08-21 14:02 UTC, gerrycampion commented on resources/schema/MetaVariables.md
> +## define_variable_has_comment
should be define_vlm_has_comment

2023-08-21 15:17 UTC, gerrycampion approved these changes

2023-08-21 15:53 UTC, merged

2023-08-28 19:36 UTC, gerrycampion commented
For QA, I tried testing with the attached rule and data. I expect LB to return a issue for LBCAT, but instead I am receiving an error:
```json
[
  {
    "executionStatus": "execution_error",
    "domain": "LB",
    "variables": [],
    "message": "rule execution error",
    "errors": [
      {
        "error": "Column not found in data",
        "message": "ordinal"
      }
    ]
  }
]
```
[Rule (3).zip](https://github.com/cdisc-org/cdisc-rules-engine/files/12457691/Rule.3.zip)

The same data is also available in the prod rule editor and sharepoint under SD1149

2023-08-29 15:20 UTC, nhaydel commented
@gerrycampion with the latest update we are no longer seeing this issue. I believe it was an issue with how we were passing library metadata to the rule builders