Update test_rule.py
cdisc-org/cdisc-rules-engine pull request #531
Opened 2023-09-04 15:12 UTC by dostiep

This PR is to fix an issue when using dataset path for the test fucntion in a Windows environment command line.

2023-09-07 15:28 UTC, gerrycampion requested changes

2023-09-07 15:28 UTC, gerrycampion commented on scripts/test_rule.py
> +                    os.path.join(directory, dataset.filename).replace(os.sep, '/'),
The linter is complaining about this line. See more info about formatting and pre-commits here: https://github.com/cdisc-org/cdisc-rules-engine#code-formatter

2023-09-07 15:28 UTC, gerrycampion commented on scripts/test_rule.py
> +                    os.path.join(directory, dataset.filename).replace(os.sep, '/'),
This fix works, but it defers this OS file-separator issues. It looks like the actual cause of the issue is here:

https://github.com/cdisc-org/cdisc-rules-engine/blob/3c18a77ca164259d20d70f4710b2b094e4a85a76/cdisc_rules_engine/services/data_services/dummy_data_service.py#L51

Instead, it should be something like: 
```python
dataset_name = os.path.basename(dataset_name)
```

2023-09-07 15:32 UTC, dostiep commented
dataset_name = os.path.split(path)[-1]  would probably work

2023-09-07 16:12 UTC, gerrycampion commented
> dataset_name = os.path.split(path)[-1] would probably work

Either should work fine. This is sort of what basename does, so basename is just a shortcut

2023-09-08 07:29 UTC, dostiep commented
Thanks for the tip :) 

I'll update the proper program instead and will create a new PR along with the updates for Dataset-JSON.

2023-09-08 07:29 UTC, closed without merging

2023-09-08 13:35 UTC, gerrycampion commented
@dostiep In the future, you don't need to create a new PR to make updates for the same issue. You can just push the updates to the issue branch and rerequest review and they should show up in the current PR.  It should be a bit easier.