Changed valueError from local rule validation to logger warning
cdisc-org/cdisc-rules-engine pull request #697
Opened 2024-05-08 17:29 UTC by SFJohnson24

2024-05-14 16:16 UTC, gerrycampion requested changes

2024-05-14 16:16 UTC, gerrycampion commented on scripts/script_utils.py
> +                "-r rule flag and in local directory or is a duplicate rule. Skipping..."
I think skipping a rule in the local directory is somewhat typical and should actually be downgraded to `info`. Detecting a duplicate rule should be an error.  These 2 scenarios should be separate. Also, I don't see how this is detecting duplicate rules at all, but maybe I'm misunderstanding.

2024-05-14 16:16 UTC, gerrycampion commented on scripts/script_utils.py
> +        if missing_rules:
I don't think this line is necessary

2024-05-15 16:14 UTC, SFJohnson24 commented on scripts/script_utils.py
>          engine_logger.warning(
I believe not specifying a rule and running all rules in the directory also should not be a warning.  I want to be consistent with the level of log.  I was going to change it to info.  Would you agree with the downgrade?

2024-05-17 16:41 UTC, merged